package arm.node;

@:keep class NodeTreeTest extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		name = "NodeTreeTest";
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _GetTransform = new armory.logicnode.GetTransformNode(this);
		_GetTransform.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetTransform.addOutputs([new armory.logicnode.NullNode(this)]);
		var _KeyboardState = new armory.logicnode.KeyboardNode(this);
		_KeyboardState.property0 = "Started";
		_KeyboardState.property1 = "a";
		_KeyboardState.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		var _TranslateOnLocalAxis = new armory.logicnode.TranslateOnLocalAxisNode(this);
		_TranslateOnLocalAxis.addInput(new armory.logicnode.NullNode(this), 0);
		_TranslateOnLocalAxis.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_TranslateOnLocalAxis.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_TranslateOnLocalAxis.addInput(new armory.logicnode.IntegerNode(this, 0), 0);
		_TranslateOnLocalAxis.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_TranslateOnLocalAxis.addOutputs([new armory.logicnode.NullNode(this)]);
		var _ApplyForce = new armory.logicnode.ApplyForceNode(this);
		_ApplyForce.addInput(new armory.logicnode.NullNode(this), 0);
		_ApplyForce.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_ApplyForce.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_ApplyForce.addOutputs([new armory.logicnode.NullNode(this)]);
		var _AnimationState = new armory.logicnode.AnimationStateNode(this);
		_AnimationState.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_AnimationState.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_AnimationState.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_AnimationState.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		var _Sequence = new armory.logicnode.SequenceNode(this);
		_Sequence.addInput(new armory.logicnode.NullNode(this), 0);
		var _PlayAction = new armory.logicnode.PlayActionNode(this);
		_PlayAction.addInput(new armory.logicnode.NullNode(this), 0);
		_PlayAction.addInput(new armory.logicnode.ObjectNode(this, "Player_Mesh"), 0);
		_PlayAction.addInput(new armory.logicnode.StringNode(this, "Player ArmatureAction"), 0);
		_PlayAction.addInput(new armory.logicnode.FloatNode(this, 0.20000000298023224), 0);
		_PlayAction.addOutputs([new armory.logicnode.NullNode(this)]);
		_PlayAction.addOutputs([new armory.logicnode.NullNode(this)]);
		var _KeyboardState_001 = new armory.logicnode.KeyboardNode(this);
		_KeyboardState_001.property0 = "Started";
		_KeyboardState_001.property1 = "space";
		_KeyboardState_001.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		var _SetVelocity = new armory.logicnode.SetVelocityNode(this);
		_SetVelocity.addInput(new armory.logicnode.NullNode(this), 0);
		_SetVelocity.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 1.0, 1.0, 1.0), 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetVelocity.addInput(new armory.logicnode.VectorNode(this, 1.0, 1.0, 1.0), 0);
		_SetVelocity.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetLocation = new armory.logicnode.SetLocationNode(this);
		_SetLocation.addInput(new armory.logicnode.NullNode(this), 0);
		_SetLocation.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetLocation.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_SetLocation.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetProperty = new armory.logicnode.GetPropertyNode(this);
		_GetProperty.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetProperty.addInput(new armory.logicnode.StringNode(this, ""), 0);
		_GetProperty.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetHaxeProperty = new armory.logicnode.GetHaxePropertyNode(this);
		_GetHaxeProperty.addInput(new armory.logicnode.NullNode(this), 0);
		_GetHaxeProperty.addInput(new armory.logicnode.StringNode(this, ""), 0);
		_GetHaxeProperty.addOutputs([new armory.logicnode.NullNode(this)]);
		var _OnTimer = new armory.logicnode.OnTimerNode(this);
		_OnTimer.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_OnTimer.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_OnTimer.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetObject = new armory.logicnode.GetObjectNode(this);
		_GetObject.addInput(new armory.logicnode.StringNode(this, ""), 0);
		_GetObject.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		var _AddTrait = new armory.logicnode.AddTraitNode(this);
		_AddTrait.addInput(new armory.logicnode.NullNode(this), 0);
		_AddTrait.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		var _Trait = new armory.logicnode.TraitNode(this);
		_Trait.property0 = "";
		_Trait.addOutputs([_AddTrait]);
		_AddTrait.addInput(_Trait, 0);
		_AddTrait.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetTrait = new armory.logicnode.GetTraitNode(this);
		_GetTrait.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetTrait.addInput(new armory.logicnode.StringNode(this, ""), 0);
		_GetTrait.addOutputs([new armory.logicnode.NullNode(this)]);
		var _AnimationState_001 = new armory.logicnode.AnimationStateNode(this);
		_AnimationState_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_AnimationState_001.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_AnimationState_001.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_AnimationState_001.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		var _PlayAction_001 = new armory.logicnode.PlayActionNode(this);
		_PlayAction_001.addInput(new armory.logicnode.NullNode(this), 0);
		_PlayAction_001.addInput(new armory.logicnode.ObjectNode(this, "TitleText backup"), 0);
		_PlayAction_001.addInput(new armory.logicnode.StringNode(this, "ShearAnim"), 0);
		_PlayAction_001.addInput(new armory.logicnode.FloatNode(this, 0.20000000298023224), 0);
		_PlayAction_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_PlayAction_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Mesh = new armory.logicnode.MeshNode(this);
		_Mesh.property0 = None;
		_Mesh.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetMesh = new armory.logicnode.GetMeshNode(this);
		_GetMesh.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetMesh.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Scene = new armory.logicnode.SceneNode(this);
		_Scene.property0 = None;
		_Scene.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetScene = new armory.logicnode.SetSceneNode(this);
		_SetScene.addInput(new armory.logicnode.NullNode(this), 0);
		_SetScene.addInput(new armory.logicnode.NullNode(this), 0);
		_SetScene.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetScene.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		var _SendGlobalEvent = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent.addInput(new armory.logicnode.NullNode(this), 0);
		_SendGlobalEvent.addInput(new armory.logicnode.StringNode(this, ""), 0);
		_SendGlobalEvent.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SendEvent = new armory.logicnode.SendEventNode(this);
		_SendEvent.addInput(new armory.logicnode.NullNode(this), 0);
		_SendEvent.addInput(new armory.logicnode.StringNode(this, ""), 0);
		_SendEvent.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SendEvent.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Shutdown = new armory.logicnode.ShutdownNode(this);
		_Shutdown.addInput(new armory.logicnode.NullNode(this), 0);
		_Shutdown.addOutputs([new armory.logicnode.NullNode(this)]);
		var _RotateObject = new armory.logicnode.RotateObjectNode(this);
		_RotateObject.addInput(new armory.logicnode.NullNode(this), 0);
		_RotateObject.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_RotateObject.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_RotateObject.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetCamera = new armory.logicnode.SetCameraNode(this);
		_SetCamera.addInput(new armory.logicnode.NullNode(this), 0);
		_SetCamera.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetCamera.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SpawnObject = new armory.logicnode.SpawnObjectNode(this);
		_SpawnObject.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnObject.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SpawnObject.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnObject.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_SpawnObject.addOutputs([new armory.logicnode.NullNode(this)]);
		_SpawnObject.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		var _Time = new armory.logicnode.TimeNode(this);
		_Time.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Time.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		var _CastPhysicsRay = new armory.logicnode.CastPhysicsRayNode(this);
		_CastPhysicsRay.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_CastPhysicsRay.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_CastPhysicsRay.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		_CastPhysicsRay.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_CastPhysicsRay.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		var _RemoveObject = new armory.logicnode.RemoveObjectNode(this);
		_RemoveObject.addInput(new armory.logicnode.NullNode(this), 0);
		_RemoveObject.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_RemoveObject.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetMaterial = new armory.logicnode.GetMaterialNode(this);
		_GetMaterial.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetMaterial.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Material = new armory.logicnode.MaterialNode(this);
		_Material.property0 = "";
		_Material.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetMaterial = new armory.logicnode.SetMaterialNode(this);
		_SetMaterial.addInput(new armory.logicnode.NullNode(this), 0);
		_SetMaterial.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetMaterial.addInput(new armory.logicnode.NullNode(this), 0);
		_SetMaterial.addOutputs([new armory.logicnode.NullNode(this)]);
		var _RemoveTrait = new armory.logicnode.RemoveTraitNode(this);
		_RemoveTrait.addInput(new armory.logicnode.NullNode(this), 0);
		_RemoveTrait.addInput(new armory.logicnode.NullNode(this), 0);
		_RemoveTrait.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetCameraFOV = new armory.logicnode.SetCameraFovNode(this);
		_SetCameraFOV.addInput(new armory.logicnode.NullNode(this), 0);
		_SetCameraFOV.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetCameraFOV.addInput(new armory.logicnode.FloatNode(this, 0.8500000238418579), 0);
		_SetCameraFOV.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetCamera_001 = new armory.logicnode.SetCameraNode(this);
		_SetCamera_001.addInput(new armory.logicnode.NullNode(this), 0);
		_SetCamera_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetCamera_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _ClearParent = new armory.logicnode.ClearParentNode(this);
		_ClearParent.addInput(new armory.logicnode.NullNode(this), 0);
		_ClearParent.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_ClearParent.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_ClearParent.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetParent = new armory.logicnode.SetParentNode(this);
		_SetParent.addInput(new armory.logicnode.NullNode(this), 0);
		_SetParent.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetParent.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetParent.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetCameraFOV_001 = new armory.logicnode.SetCameraFovNode(this);
		_SetCameraFOV_001.addInput(new armory.logicnode.NullNode(this), 0);
		_SetCameraFOV_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetCameraFOV_001.addInput(new armory.logicnode.FloatNode(this, 0.8500000238418579), 0);
		_SetCameraFOV_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _OnMouse = new armory.logicnode.OnMouseNode(this);
		_OnMouse.property0 = "Down";
		_OnMouse.property1 = "left";
		_OnMouse.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Time_001 = new armory.logicnode.TimeNode(this);
		_Time_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Time_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		var _Random_Float_ = new armory.logicnode.RandomFloatNode(this);
		_Random_Float_.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Random_Float_.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		_Random_Float_.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		var _SpawnObject_001 = new armory.logicnode.SpawnObjectNode(this);
		_SpawnObject_001.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnObject_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SpawnObject_001.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnObject_001.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_SpawnObject_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_SpawnObject_001.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		var _LookAt = new armory.logicnode.LookAtNode(this);
		_LookAt.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_LookAt.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_LookAt.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		var _SetScene_001 = new armory.logicnode.SetSceneNode(this);
		_SetScene_001.addInput(new armory.logicnode.NullNode(this), 0);
		_SetScene_001.addInput(new armory.logicnode.NullNode(this), 0);
		_SetScene_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetScene_001.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		var _RemoveActiveScene = new armory.logicnode.RemoveActiveSceneNode(this);
		_RemoveActiveScene.addInput(new armory.logicnode.NullNode(this), 0);
		_RemoveActiveScene.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetScene_002 = new armory.logicnode.SetSceneNode(this);
		_SetScene_002.addInput(new armory.logicnode.NullNode(this), 0);
		_SetScene_002.addInput(new armory.logicnode.NullNode(this), 0);
		_SetScene_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetScene_002.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		var _SpawnScene_001 = new armory.logicnode.SpawnSceneNode(this);
		_SpawnScene_001.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnScene_001.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnScene_001.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnScene_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_SpawnScene_001.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		var _CastPhysicsRay_001 = new armory.logicnode.CastPhysicsRayNode(this);
		_CastPhysicsRay_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_CastPhysicsRay_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_CastPhysicsRay_001.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		_CastPhysicsRay_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_CastPhysicsRay_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		var _SpawnScene = new armory.logicnode.SpawnSceneNode(this);
		_SpawnScene.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnScene.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnScene.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnScene.addOutputs([new armory.logicnode.NullNode(this)]);
		_SpawnScene.addOutputs([new armory.logicnode.ObjectNode(this, "")]);
		var _PlaySound = new armory.logicnode.PlaySoundRawNode(this);
		_PlaySound.property0 = None;
		_PlaySound.addInput(new armory.logicnode.NullNode(this), 0);
		_PlaySound.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetVisible = new armory.logicnode.SetVisibleNode(this);
		_SetVisible.addInput(new armory.logicnode.NullNode(this), 0);
		_SetVisible.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetVisible.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_SetVisible.addOutputs([new armory.logicnode.NullNode(this)]);
		var _BoneIK = new armory.logicnode.BoneIKNode(this);
		_BoneIK.addInput(new armory.logicnode.NullNode(this), 0);
		_BoneIK.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_BoneIK.addInput(new armory.logicnode.StringNode(this, ""), 0);
		_BoneIK.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_BoneIK.addOutputs([new armory.logicnode.NullNode(this)]);
		var _BoneFK = new armory.logicnode.BoneFKNode(this);
		_BoneFK.addInput(new armory.logicnode.NullNode(this), 0);
		_BoneFK.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_BoneFK.addInput(new armory.logicnode.StringNode(this, ""), 0);
		_BoneFK.addInput(new armory.logicnode.NullNode(this), 0);
		_BoneFK.addOutputs([new armory.logicnode.NullNode(this)]);
		var _RotateObject_001 = new armory.logicnode.RotateObjectNode(this);
		_RotateObject_001.addInput(new armory.logicnode.NullNode(this), 0);
		_RotateObject_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_RotateObject_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0), 0);
		_RotateObject_001.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}